version: '3'

services:
  web:
    build: ./docker-nginx
    ports:
      - 8080:80
    depends_on:
      - app
    volumes:
      - ../html:/var/www/html
      - ./docker-nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - app

  app:
    build: ./docker-php
    volumes:
      - ../html:/var/www/html

